### ISSUE TITLE
Figure out Firebase

### ISSUE THREAD

**Issue by SeleniumK** [Trivia-Crossroads/triviacrossroads#1]
Basic understanding for implementation across pages

**Comment by dtolmie** [comment]
Here's the quickstart guide that Selena put in Slack.

- https://www.firebase.com/docs/web/quickstart.html

Here are the two examples Scott sent me in Slack:

- Ex 1:
  - *Dig into the Public folder for all of the JS files… specifically look into the index.js*
  -  https://github.com/ThirdFoundation/scratchpost
- Ex 2
  - *Here’s another example; Darcy’s group used Firebase as well
  - https://github.com/kjs222/BestOf

Digested info to come…

**Comment by dtolmie** [comment]
Okay. I've figure out the very basics of Firebase. I've added the following comments in people.js as a rough guide to pushing data to FB and retrieving all the objects from FB. FB does support much more targeted queries, so we may want to look into those as needed.

```
// Example of referencing the Person DB in Firebase
var fbPerson = new Firebase('https://trivia-crossroads.firebaseio.com/Person');

//Example of pulling the objects from Person
fbPerson.on("value", function(snapshot) {
  console.log(snapshot.val());
}, function (errorObject) {
  console.log("The read failed: " + errorObject.code);
});

//Example of pushing new content to People
//Do NOT use .set, as it will overwrite all existing data with what you're setting.
fbPerson.push({name: 'Selena', gender: 'female'});

// By setting the URL to a specific FB UUID, we can access that object directly
//var fbPerson = new Firebase('https://trivia-crossroads.firebaseio.com/Person/-K3H95UMwdDSzN0ZbH9d');
```

**Comment by dtolmie** [comment]
```
// Here's an example of filtering by key/value when querying FB
fbPerson.orderByChild("gender").equalTo('male').on("value", function(snapshot) {
  console.log(snapshot.val());
}, function (errorObject) {
  console.log("The read failed: " + errorObject.code);
});
```

**Comment by dtolmie** [comment]
I've moved the examples to FirebaseExamples.js

**Comment by dtolmie** [comment]
I've added an example of setting the UUID to a cookie. See FirebaseExamples.js for additional forthcoming examples relevant to this project.

**Comment by dtolmie** [comment]
We've got the basics of the code for interfacing with firebase like we would localstorage.
