### ISSUE TITLE
content for about me 

### ISSUE THREAD

**Issue by SeleniumK** [Trivia-Crossroads/triviacrossroads#23]

**Comment by dtolmie** [comment]
So, we each need to create our own bios… How long are we thinking? And, what tone? As much as possibly, we should aim for similar length and tone.

**Comment by ivarmlee11** [comment]
I want to remove the left <aside>

**Comment by SeleniumK** [comment]
We should all write our own bios. Maybe 2 or 3 sentences.  What tone do you think?

**Comment by ivarmlee11** [comment]
Hi! I'm Ivar. I enjoy live comedy, chilly nights, and running. Looking at my podcast feed would tell you more about me than I could.    (Completely willing to change tone, add more info)
