### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by SeleniumK** [Trivia-Crossroads/triviacrossroads#24]

**Comment by willierichardson72** [comment]
![silverstar](https://cloud.githubusercontent.com/assets/15300813/11202584/7d5bbeb0-8c9e-11e5-98be-193740ec57a6.jpg)
 Here is a picture of me for the "About Us" page

**Comment by willierichardson72** [comment]
Logo Completed using Flexbox.  I used Chewy Cursive Font with Logo framed by two images.
