### ISSUE TITLE
Header formatting

### ISSUE THREAD

**Issue by SeleniumK** [Trivia-Crossroads/triviacrossroads#25]

**Comment by ivarmlee11** [comment]
Going to try to push the nav bar to the bottom of the header so that it's flush

**Comment by dtolmie** [comment]
@ivarmlee11 I just saw your comment. Sounds great! I removed some padding to get it flush left, but didn't want to mess with your nav bar. I think it would be great to make it flush to the bottom, though.

**Comment by dtolmie** [comment]
I've styled the heading above the nav bar and added it to all pages.

**Comment by dtolmie** [comment]
@ivarmlee11 Per our conversation, I'm closing this issue and opening one specific to your Nav work.
