### ISSUE TITLE
People form accepts blank input

### ISSUE THREAD

**Issue by dtolmie** [Trivia-Crossroads/triviacrossroads#27]
We need to add some degree of input validation to the form. Currently, we can submit blank forms resulting in a nameless entry in the database with default form values.

We should probably add HTML input validation in addition to making sure an object has values (neither null nor undefined) before writing it to the array.

**Comment by dtolmie** [comment]
In the above pull request, I added the *required* property to the HTML forms. To truly have quality code, we should still do input validation in the JS before writing to the database. That said, I think we should hold off until we've tackled higher priority issues. We can add validation in the JS if we have time. For now, one can't accidentally add blank submissions.

**Comment by SeleniumK** [comment]
Some validation with email and name in place. Leave the rest for stretch goals.
