### ISSUE TITLE
Code Style/Cleanup

### ISSUE THREAD

**Issue by scotist** [Trivia-Crossroads/triviacrossroads#76]
I created a new branch called "cleanup". At some point we should go through all our code, checking for style and indentation issues, unneeded comments, useless lines etc, and push to this branch for a clean copy.

**Comment by ivarmlee11** [comment]
When I copied over the flexbox and nav bar stuff I brought over a ton of commented stuff that we may want to delete

**Comment by dtolmie** [comment]
We'll probably want to either merge in tonight's code or recreate the branch before significant cleanup happens. Some of the code has been under active development since the branch was created.
