### ISSUE TITLE
new content for aside containers on Signup page

### ISSUE THREAD

**Issue by scotist** [Trivia-Crossroads/triviacrossroads#83]

**Comment by dtolmie** [comment]
I think with the background image @willierichardson72 added, this issue is ready to close. When pull reqeust #93 is merged, you can see what it looks like. There really isn't room for additional content beyond Willie's background pic, especially on the people page.

**Comment by dtolmie** [comment]
Nevermind!  I know what page you mean. Yeah. @willierichardson72 has a pic to use, and we'll drop that in same as the people and event pages in the AM. I'm reaching my end of day, even if I'm going home to a dark house!

**Comment by willierichardson72** [comment]
Added image!
