### ISSUE TITLE
Padding, margins, and corners inconsistent within pages.

### ISSUE THREAD

**Issue by dtolmie** [Trivia-Crossroads/triviacrossroads#95]
Our internal padding, margins, and corners are inconsistent within our pages. We should decide how we want them to look, then standardize…and document in the style guide. I have some thoughts/preferences, but none I'm too attached to. Let's talk about this in the AM.

**Comment by SeleniumK** [comment]
Sounds good.

**Comment by SeleniumK** [comment]
Merging this issue with style guide
