### ISSUE TITLE
Did you know?

### ISSUE THREAD

**Issue by dtolmie** [Trivia-Crossroads/triviacrossroads#97]
So… I really like the *Did you know?* bit. If we have the time and motivation, it would be great to…

1. Make the *trivium means three roads* come up for any first time visitor based on super cookie
2. Shuffle the deck of questions so one doesn't get repeats until one has seem all "facts" — I have the code for this
3. Make the "facts" appear on all pages
4. #s 2 & 3 would require storing the user's deck of facts in local storage, but that's easy.

Thoughts?

**Comment by scotist** [comment]
I like these ideas; let's see what we can do tomorrow!

**Comment by dtolmie** [comment]
Mission Accomplished!! :metal:
